# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /usr/prakt/p116/GPULabProj

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /usr/prakt/p116/GPULabProj

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /usr/prakt/p116/GPULabProj/CMakeFiles /usr/prakt/p116/GPULabProj/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /usr/prakt/p116/GPULabProj/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named auxiliaryCPU

# Build rule for target.
auxiliaryCPU: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 auxiliaryCPU
.PHONY : auxiliaryCPU

# fast build rule for target.
auxiliaryCPU/fast:
	$(MAKE) -f CMakeFiles/auxiliaryCPU.dir/build.make CMakeFiles/auxiliaryCPU.dir/build
.PHONY : auxiliaryCPU/fast

#=============================================================================
# Target rules for targets named auxiliaryGPU

# Build rule for target.
auxiliaryGPU: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 auxiliaryGPU
.PHONY : auxiliaryGPU

# fast build rule for target.
auxiliaryGPU/fast:
	$(MAKE) -f CMakeFiles/auxiliaryGPU.dir/build.make CMakeFiles/auxiliaryGPU.dir/build
.PHONY : auxiliaryGPU/fast

#=============================================================================
# Target rules for targets named filesystem

# Build rule for target.
filesystem: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 filesystem
.PHONY : filesystem

# fast build rule for target.
filesystem/fast:
	$(MAKE) -f CMakeFiles/filesystem.dir/build.make CMakeFiles/filesystem.dir/build
.PHONY : filesystem/fast

#=============================================================================
# Target rules for targets named flow

# Build rule for target.
flow: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 flow
.PHONY : flow

# fast build rule for target.
flow/fast:
	$(MAKE) -f CMakeFiles/flow.dir/build.make CMakeFiles/flow.dir/build
.PHONY : flow/fast

#=============================================================================
# Target rules for targets named flowlib

# Build rule for target.
flowlib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 flowlib
.PHONY : flowlib

# fast build rule for target.
flowlib/fast:
	$(MAKE) -f CMakeFiles/flowlib.dir/build.make CMakeFiles/flowlib.dir/build
.PHONY : flowlib/fast

#=============================================================================
# Target rules for targets named flowlibGPU

# Build rule for target.
flowlibGPU: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 flowlibGPU
.PHONY : flowlibGPU

# fast build rule for target.
flowlibGPU/fast:
	$(MAKE) -f CMakeFiles/flowlibGPU.dir/build.make CMakeFiles/flowlibGPU.dir/build
.PHONY : flowlibGPU/fast

#=============================================================================
# Target rules for targets named imagepyramid

# Build rule for target.
imagepyramid: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 imagepyramid
.PHONY : imagepyramid

# fast build rule for target.
imagepyramid/fast:
	$(MAKE) -f CMakeFiles/imagepyramid.dir/build.make CMakeFiles/imagepyramid.dir/build
.PHONY : imagepyramid/fast

#=============================================================================
# Target rules for targets named imagepyramidGPU

# Build rule for target.
imagepyramidGPU: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 imagepyramidGPU
.PHONY : imagepyramidGPU

# fast build rule for target.
imagepyramidGPU/fast:
	$(MAKE) -f CMakeFiles/imagepyramidGPU.dir/build.make CMakeFiles/imagepyramidGPU.dir/build
.PHONY : imagepyramidGPU/fast

#=============================================================================
# Target rules for targets named linearoperations

# Build rule for target.
linearoperations: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 linearoperations
.PHONY : linearoperations

# fast build rule for target.
linearoperations/fast:
	$(MAKE) -f CMakeFiles/linearoperations.dir/build.make CMakeFiles/linearoperations.dir/build
.PHONY : linearoperations/fast

#=============================================================================
# Target rules for targets named linearoperationsGPU

# Build rule for target.
linearoperationsGPU: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 linearoperationsGPU
.PHONY : linearoperationsGPU

# fast build rule for target.
linearoperationsGPU/fast:
	$(MAKE) -f CMakeFiles/linearoperationsGPU.dir/build.make CMakeFiles/linearoperationsGPU.dir/build
.PHONY : linearoperationsGPU/fast

#=============================================================================
# Target rules for targets named superresolution

# Build rule for target.
superresolution: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 superresolution
.PHONY : superresolution

# fast build rule for target.
superresolution/fast:
	$(MAKE) -f CMakeFiles/superresolution.dir/build.make CMakeFiles/superresolution.dir/build
.PHONY : superresolution/fast

#=============================================================================
# Target rules for targets named superresolutionlib

# Build rule for target.
superresolutionlib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 superresolutionlib
.PHONY : superresolutionlib

# fast build rule for target.
superresolutionlib/fast:
	$(MAKE) -f CMakeFiles/superresolutionlib.dir/build.make CMakeFiles/superresolutionlib.dir/build
.PHONY : superresolutionlib/fast

#=============================================================================
# Target rules for targets named superresolutionlibGPU

# Build rule for target.
superresolutionlibGPU: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 superresolutionlibGPU
.PHONY : superresolutionlibGPU

# fast build rule for target.
superresolutionlibGPU/fast:
	$(MAKE) -f CMakeFiles/superresolutionlibGPU.dir/build.make CMakeFiles/superresolutionlibGPU.dir/build
.PHONY : superresolutionlibGPU/fast

# target to build an object file
src/auxiliary/debug.o:
	$(MAKE) -f CMakeFiles/auxiliaryCPU.dir/build.make CMakeFiles/auxiliaryCPU.dir/src/auxiliary/debug.o
.PHONY : src/auxiliary/debug.o

# target to preprocess a source file
src/auxiliary/debug.i:
	$(MAKE) -f CMakeFiles/auxiliaryCPU.dir/build.make CMakeFiles/auxiliaryCPU.dir/src/auxiliary/debug.i
.PHONY : src/auxiliary/debug.i

# target to generate assembly for a file
src/auxiliary/debug.s:
	$(MAKE) -f CMakeFiles/auxiliaryCPU.dir/build.make CMakeFiles/auxiliaryCPU.dir/src/auxiliary/debug.s
.PHONY : src/auxiliary/debug.s

# target to build an object file
src/filesystem/filesystem.o:
	$(MAKE) -f CMakeFiles/filesystem.dir/build.make CMakeFiles/filesystem.dir/src/filesystem/filesystem.o
.PHONY : src/filesystem/filesystem.o

# target to preprocess a source file
src/filesystem/filesystem.i:
	$(MAKE) -f CMakeFiles/filesystem.dir/build.make CMakeFiles/filesystem.dir/src/filesystem/filesystem.i
.PHONY : src/filesystem/filesystem.i

# target to generate assembly for a file
src/filesystem/filesystem.s:
	$(MAKE) -f CMakeFiles/filesystem.dir/build.make CMakeFiles/filesystem.dir/src/filesystem/filesystem.s
.PHONY : src/filesystem/filesystem.s

# target to build an object file
src/flow_main.o:
	$(MAKE) -f CMakeFiles/flow.dir/build.make CMakeFiles/flow.dir/src/flow_main.o
.PHONY : src/flow_main.o

# target to preprocess a source file
src/flow_main.i:
	$(MAKE) -f CMakeFiles/flow.dir/build.make CMakeFiles/flow.dir/src/flow_main.i
.PHONY : src/flow_main.i

# target to generate assembly for a file
src/flow_main.s:
	$(MAKE) -f CMakeFiles/flow.dir/build.make CMakeFiles/flow.dir/src/flow_main.s
.PHONY : src/flow_main.s

# target to build an object file
src/flowlib/flowio.o:
	$(MAKE) -f CMakeFiles/flowlib.dir/build.make CMakeFiles/flowlib.dir/src/flowlib/flowio.o
.PHONY : src/flowlib/flowio.o

# target to preprocess a source file
src/flowlib/flowio.i:
	$(MAKE) -f CMakeFiles/flowlib.dir/build.make CMakeFiles/flowlib.dir/src/flowlib/flowio.i
.PHONY : src/flowlib/flowio.i

# target to generate assembly for a file
src/flowlib/flowio.s:
	$(MAKE) -f CMakeFiles/flowlib.dir/build.make CMakeFiles/flowlib.dir/src/flowlib/flowio.s
.PHONY : src/flowlib/flowio.s

# target to build an object file
src/flowlib/flowlib.o:
	$(MAKE) -f CMakeFiles/flowlib.dir/build.make CMakeFiles/flowlib.dir/src/flowlib/flowlib.o
.PHONY : src/flowlib/flowlib.o

# target to preprocess a source file
src/flowlib/flowlib.i:
	$(MAKE) -f CMakeFiles/flowlib.dir/build.make CMakeFiles/flowlib.dir/src/flowlib/flowlib.i
.PHONY : src/flowlib/flowlib.i

# target to generate assembly for a file
src/flowlib/flowlib.s:
	$(MAKE) -f CMakeFiles/flowlib.dir/build.make CMakeFiles/flowlib.dir/src/flowlib/flowlib.s
.PHONY : src/flowlib/flowlib.s

# target to build an object file
src/flowlib/flowlib_cpu_sor.o:
	$(MAKE) -f CMakeFiles/flowlib.dir/build.make CMakeFiles/flowlib.dir/src/flowlib/flowlib_cpu_sor.o
.PHONY : src/flowlib/flowlib_cpu_sor.o

# target to preprocess a source file
src/flowlib/flowlib_cpu_sor.i:
	$(MAKE) -f CMakeFiles/flowlib.dir/build.make CMakeFiles/flowlib.dir/src/flowlib/flowlib_cpu_sor.i
.PHONY : src/flowlib/flowlib_cpu_sor.i

# target to generate assembly for a file
src/flowlib/flowlib_cpu_sor.s:
	$(MAKE) -f CMakeFiles/flowlib.dir/build.make CMakeFiles/flowlib.dir/src/flowlib/flowlib_cpu_sor.s
.PHONY : src/flowlib/flowlib_cpu_sor.s

# target to build an object file
src/imagepyramid/imagepyramidcpu.o:
	$(MAKE) -f CMakeFiles/imagepyramid.dir/build.make CMakeFiles/imagepyramid.dir/src/imagepyramid/imagepyramidcpu.o
.PHONY : src/imagepyramid/imagepyramidcpu.o

# target to preprocess a source file
src/imagepyramid/imagepyramidcpu.i:
	$(MAKE) -f CMakeFiles/imagepyramid.dir/build.make CMakeFiles/imagepyramid.dir/src/imagepyramid/imagepyramidcpu.i
.PHONY : src/imagepyramid/imagepyramidcpu.i

# target to generate assembly for a file
src/imagepyramid/imagepyramidcpu.s:
	$(MAKE) -f CMakeFiles/imagepyramid.dir/build.make CMakeFiles/imagepyramid.dir/src/imagepyramid/imagepyramidcpu.s
.PHONY : src/imagepyramid/imagepyramidcpu.s

# target to build an object file
src/imagepyramid/imagepyramidgpu.o:
	$(MAKE) -f CMakeFiles/imagepyramidGPU.dir/build.make CMakeFiles/imagepyramidGPU.dir/src/imagepyramid/imagepyramidgpu.o
.PHONY : src/imagepyramid/imagepyramidgpu.o

# target to preprocess a source file
src/imagepyramid/imagepyramidgpu.i:
	$(MAKE) -f CMakeFiles/imagepyramidGPU.dir/build.make CMakeFiles/imagepyramidGPU.dir/src/imagepyramid/imagepyramidgpu.i
.PHONY : src/imagepyramid/imagepyramidgpu.i

# target to generate assembly for a file
src/imagepyramid/imagepyramidgpu.s:
	$(MAKE) -f CMakeFiles/imagepyramidGPU.dir/build.make CMakeFiles/imagepyramidGPU.dir/src/imagepyramid/imagepyramidgpu.s
.PHONY : src/imagepyramid/imagepyramidgpu.s

# target to build an object file
src/linearoperations/linearoperations.o:
	$(MAKE) -f CMakeFiles/linearoperations.dir/build.make CMakeFiles/linearoperations.dir/src/linearoperations/linearoperations.o
.PHONY : src/linearoperations/linearoperations.o

# target to preprocess a source file
src/linearoperations/linearoperations.i:
	$(MAKE) -f CMakeFiles/linearoperations.dir/build.make CMakeFiles/linearoperations.dir/src/linearoperations/linearoperations.i
.PHONY : src/linearoperations/linearoperations.i

# target to generate assembly for a file
src/linearoperations/linearoperations.s:
	$(MAKE) -f CMakeFiles/linearoperations.dir/build.make CMakeFiles/linearoperations.dir/src/linearoperations/linearoperations.s
.PHONY : src/linearoperations/linearoperations.s

# target to build an object file
src/superresolution/superresolution.o:
	$(MAKE) -f CMakeFiles/superresolutionlib.dir/build.make CMakeFiles/superresolutionlib.dir/src/superresolution/superresolution.o
.PHONY : src/superresolution/superresolution.o

# target to preprocess a source file
src/superresolution/superresolution.i:
	$(MAKE) -f CMakeFiles/superresolutionlib.dir/build.make CMakeFiles/superresolutionlib.dir/src/superresolution/superresolution.i
.PHONY : src/superresolution/superresolution.i

# target to generate assembly for a file
src/superresolution/superresolution.s:
	$(MAKE) -f CMakeFiles/superresolutionlib.dir/build.make CMakeFiles/superresolutionlib.dir/src/superresolution/superresolution.s
.PHONY : src/superresolution/superresolution.s

# target to build an object file
src/superresolution_main.o:
	$(MAKE) -f CMakeFiles/superresolution.dir/build.make CMakeFiles/superresolution.dir/src/superresolution_main.o
.PHONY : src/superresolution_main.o

# target to preprocess a source file
src/superresolution_main.i:
	$(MAKE) -f CMakeFiles/superresolution.dir/build.make CMakeFiles/superresolution.dir/src/superresolution_main.i
.PHONY : src/superresolution_main.i

# target to generate assembly for a file
src/superresolution_main.s:
	$(MAKE) -f CMakeFiles/superresolution.dir/build.make CMakeFiles/superresolution.dir/src/superresolution_main.s
.PHONY : src/superresolution_main.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... auxiliaryCPU"
	@echo "... auxiliaryGPU"
	@echo "... edit_cache"
	@echo "... filesystem"
	@echo "... flow"
	@echo "... flowlib"
	@echo "... flowlibGPU"
	@echo "... imagepyramid"
	@echo "... imagepyramidGPU"
	@echo "... linearoperations"
	@echo "... linearoperationsGPU"
	@echo "... rebuild_cache"
	@echo "... superresolution"
	@echo "... superresolutionlib"
	@echo "... superresolutionlibGPU"
	@echo "... src/auxiliary/debug.o"
	@echo "... src/auxiliary/debug.i"
	@echo "... src/auxiliary/debug.s"
	@echo "... src/filesystem/filesystem.o"
	@echo "... src/filesystem/filesystem.i"
	@echo "... src/filesystem/filesystem.s"
	@echo "... src/flow_main.o"
	@echo "... src/flow_main.i"
	@echo "... src/flow_main.s"
	@echo "... src/flowlib/flowio.o"
	@echo "... src/flowlib/flowio.i"
	@echo "... src/flowlib/flowio.s"
	@echo "... src/flowlib/flowlib.o"
	@echo "... src/flowlib/flowlib.i"
	@echo "... src/flowlib/flowlib.s"
	@echo "... src/flowlib/flowlib_cpu_sor.o"
	@echo "... src/flowlib/flowlib_cpu_sor.i"
	@echo "... src/flowlib/flowlib_cpu_sor.s"
	@echo "... src/imagepyramid/imagepyramidcpu.o"
	@echo "... src/imagepyramid/imagepyramidcpu.i"
	@echo "... src/imagepyramid/imagepyramidcpu.s"
	@echo "... src/imagepyramid/imagepyramidgpu.o"
	@echo "... src/imagepyramid/imagepyramidgpu.i"
	@echo "... src/imagepyramid/imagepyramidgpu.s"
	@echo "... src/linearoperations/linearoperations.o"
	@echo "... src/linearoperations/linearoperations.i"
	@echo "... src/linearoperations/linearoperations.s"
	@echo "... src/superresolution/superresolution.o"
	@echo "... src/superresolution/superresolution.i"
	@echo "... src/superresolution/superresolution.s"
	@echo "... src/superresolution_main.o"
	@echo "... src/superresolution_main.i"
	@echo "... src/superresolution_main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

